project:
  type: website
  output-dir: docs

website:
  title: "The Monkey Banana Project"
  comments:
    giscus:
      repo: jugheadjones10/monkey-banana
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jugheadjones10/monkey-banana
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
